name: Duplicate code

on: pull_request

jobs:
  run_if:
    if: startsWith(github.head_ref, 'deactivated')
    runs-on: ubuntu-latest
    steps:
      - name: Check for duplicate code
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "adventofcode"
