name: nanobind
run-name: ${{ github.actor }} is building Python extensions with nanobind
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
      #  with:
      #    detached: true
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python development dependency
        run: |
          sudo apt-get update
          sudo apt-get install python3.12-dev
          python -m pip install --upgrade pip
          pip install robotframework
          # pip install -r requirements.txt
      - name: Build
        run: ./build_nb.sh
      - name: Test
        working-directory: ${{github.workspace}}
        run: python3.12 nob.py
      - name: Robot
        run: PYTHONPATH=.:robot robot -d logs robot/NobTestSuite.robot
