name: nanobind
run-name: ${{ github.actor }} is building Python extensions with nanobind
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
      - name: Install Python development dependency
        run: |
          sudo apt-get update
          sudo apt-get install python3.11-dev
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
      - name: build_nanobind.sh
        run: ./build_nanobind.sh
      - name: Test nanobind extension
        run: python test_nob_nanobind_extension.py
