name: nanobind
run-name: ${{ github.actor }} is building Python extensions with nanobind
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: build_nanobind.sh
        run: ./build_nanobind.sh
