name: nob
run-name: ${{ github.actor }} is building with nobuild
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses:  actions/setup-python@v5
        with:
          python-version: '3'
        
      - name: Install dependencies
        run: sudo apt-get install libboost-all-dev libgtest-dev python3-dev python3-pybind11

      - name: Ensure python points to python3
        run: |
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
        
      - name: Build & Test
        run: |
          g++ -std=c++20 -o nob nob.cpp
          ./nob
