name: nob
run-name: ${{ github.actor }} is building with nobuild
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GoogleTest
        run: |
          sudo apt-get install libgtest-dev
      - name: Build & Test
        run: |
          g++ -std=c++20 -o nob nob.cpp
          ./nob
