name: nob
run-name: ${{ github.actor }} is building with nobuild
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install GoogleTest and GCC 13
        run: sudo apt-get install libgtest-dev gcc-13
      - name: Build & Test
        run: |
          echo alias g++='g++-13' >> ~/.bashrc
          source ~/.bashrc
          g++ -std=c++20 -o nob nob.cpp
          ./nob
