name: nob
run-name: ${{ github.actor }} is building with nobuild
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses:  actions/setup-python@v5
        with:
          python-version: '3.11'
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev libgtest-dev
          sudo apt-get install python3.11-dev libpython3.11-dev python3-pybind11 python3.11-pybind11
        
      - name: Build & Test
        run: |
          g++ -std=c++20 -o nob nob.cpp
          ./nob
