name: nob
run-name: ${{ github.actor }} is building with nobuild
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install libboost-all-dev libgtest-dev python3-pybind11
      - name: Build & Test
        run: |
          g++ -std=c++20 -o nob nob.cpp
          ./nob
